src/OCSymfony/PlatformBundle/Entity/Image.php
<?php

namespace OCSymfony\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="OCSymfony\PlatformBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    private $file;

    private $tempFileName;

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;

        // Vérification si fichier déjà présent
        if (null !== $this->url) {
            // Sauvergarde de l'extention du fichier
            $this->tempFileName = $this->url;

            // Réinitialisation des valeurs
            $this->url = null;
            $this->url = null;
        }
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {

        // Si il n'y a pas de fichier (facultatif) on sort de la fonction
        if (null === $this->file) {
            return;
        }

        // Si fichier present : suppression
        if (null !== $this->tempFileName) {
            $oldFile = $this->getUploadDir(). '/' .$this->id. '.'. $this->tempFileName;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // Déplacement du fichier dans le répertoire que l'on souhaite
        $this->file->move($this->getUploadRootDir(), $this->id .'.'. $this->url);
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload() {
        // Sauvegarde temporaire du nom du fichier
        $this->tempFileName = $this->getUploadRootDir() .'/'. $this->id .'.' .$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {

        // Récupération du nom du fichier sauvegardé
        if (file_exists($this->tempFileName)) {
            // Suppression du fichier
            unlink($this->tempFileName);
        }
    }


    public function getUploadDir() {
        // Retourne le chemin relatif vers l'image pour un navigateur
        return 'upload/img';
    }

    protected function getUploadRootDir() {
        // REtourne le chemin relatif vers l'image
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        // Si il n'y a pas de de fichier, on sort de la fonction
        if (null === $this->file) {
            return;
        }

        $this->url = $this->file->guessExtension();

        $this->alt = $this->file->getClientOriginalName();
    }

    public function getWebPath() {
        return $this->getUploadDir() .'/'. $this->getId() .'.' .$this->getUrl();
    }
}

src/OCSymfony/PlatformBundle/Form/AdvertType.php
<?php

namespace OCSymfony\PlatformBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdvertType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Liste des champs du formulaire
        $builder
            ->add('date', DateTimeType::class)
            ->add('title', TextType::class)
            ->add('author', TextType::class)
            ->add('content', CkeditorType::class)
            ->add('image', ImageType::class, array('required' => false))
            ->add('categories', EntityType::class, array(
                'class'        => 'OCSymfonyPlatformBundle:Category',
                'choice_label' => 'name',
                'multiple'     => true
            ))
            ->add('save', SubmitType::class);

        // Ajout d'un evenement
        $builder->addEventListener(FormEvents::PRE_SET_DATA,
            // Fonction déclenché lors de l'evénement
            function(FormEvent $event) {
                // Récupération de l'objet Advert
                $advert = $event->getData();

                // Sortie de la fonction si advert vaut null
                if (null === $advert) {
                    return;
                }

                // Si l'annonce n'est pas publiée ou n'existe pas
                if (!$advert->getPublished() || null === $advert->getId()) {

                    // Ajout du champ published
                    $event->getForm()->add('published', CheckboxType::class, array('required' => false));
                } else {

                    // Si non, on supprime
                    $event->getForm()->remove('published');
                }
            });
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'OCSymfony\PlatformBundle\Entity\Advert'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'ocsymfony_platformbundle_advert';
    }


}

src/OCSymfony/PlatformBundle/Controller/AdvertController.php
<?php

namespace OCSymfony\PlatformBundle\Controller;

use OCSymfony\PlatformBundle\Form\AdvertEditType;
use OCSymfony\PlatformBundle\Form\AdvertType;
use OCSymfony\PlatformBundle\Entity\Advert;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class AdvertController extends Controller {

    /**
     * Action de purge des annonces datant de X jours
     *
     * @param $days
     * @return Response
     */
    public function purgeAction(Session $session, $days) {
        // Récupération du service
        $purge = $this->get('oc_symfony_platform.purge.advert');

        //Lancement de la purge
        $traitement = $purge->purge($days);

        // Condition si la purge à eu lieux ou non
        if ($traitement) {
            // Création du message flash de confirmation
            $session->getFlashBag()->add('notice', 'Purge : Les annonces ont bien été supprimées '.$traitement);

            // Redirection vers la page d'accueil
            return $this->redirectToRoute('oc_symfony_platform_homepage');
        } else {
            // Création du message flash de confirmation
            $session->getFlashBag()->add('notice', 'Purge : Aucune annonce à supprimer');

            // Redirection vers la page d'accueil
            return $this->redirectToRoute('oc_symfony_platform_homepage');
        }

    }

    public function testAction() {
        $advert = new Advert();

        $advert->setTitle('Recherche développeur');

        $em = $this->getDoctrine()->getManager();
        $em->persist($advert);
        $em->flush();

        return new Response('Slug généré : '.$advert->getSlug());
    }

    public function editImageAction($advertId) {

        // Accès au EntityManager
        $em = $this->getDoctrine()->getManager();

        // On récupère l'annonce
        $advert = $em->getRepository('OCSymfonyPlatformBundle:Advert')->find($advertId);

        // Modification de l'url de l'image
        $advert->getImage()->setUrl('test.png');

        // Execution de la modification
        $em->flush();

        return new Response('OK');
    }

    public function menuAction($limit) {

        // Accès à l'EntityManager
        $em = $this->getDoctrine()->getManager();
        // liste du menu
        $listAdverts = $em->getRepository('OCSymfonyPlatformBundle:Advert')->findBy(array(), array('date' => 'desc'), $limit, 0);

        // Retourne le menu avec la liste
        return $this->render('OCSymfonyPlatformBundle:Advert:menu.html.twig', array('listAdverts' => $listAdverts));
    }

    public function deleteAction (Request $request,Session $session, $id) {

        // Accès à l'EntityManager
        $em = $this->getDoctrine()->getManager();

        // Récupération de l'annonce lié à l'id
        $advert = $em->getRepository('OCSymfonyPlatformBundle:Advert')->find($id);

        // Retourne un message d'erreur si l'annonce n'existe pas
        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }

        // Création d'un formulaire vide pour la protection contre la faille CSRF
        $form = $this->get('form.factory')->create();

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()){

            // Parcours des catégories et suppression
            foreach ($advert->getCategories() as $category) {
                $advert->removeCategory($category);
            }
            // Suppression de l'annonce
            $em->remove($advert);

            // Execution des suppression
            $em->flush();

            // création d'un message flash
            $session->getFlashBag()->add('notice', 'l\'annonce bien été supprimée');

            // Redirection vers la page d'accueil
            return $this->redirectToRoute('oc_symfony_platform_homepage');
        }

        // Chargement d'une page de confirmation avant la suppression
        return $this->render('OCSymfonyPlatformBundle:Advert:delete.html.twig', array(
            'advert' => $advert,
            'form' => $form->createView()
        ));
    }

    public function editAction ($id, Request $request, Session $session) {

        // Accès à l'EntityManager
        $em = $this->getDoctrine()->getManager();

        // Récupération de l'annonce
        $advert = $em->getRepository('OCSymfonyPlatformBundle:Advert')->find($id);

        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }

        // Création du formulaire de modification de l'annonce
        $form = $this->createForm(AdvertEditType::class, $advert);

        // Si la requête est en POST et que les champs sont valide
        if ($request->isMethod('POST') && $form->handleRequest($advert)->isValid()) {

            $em->flush();

            // Création d'un message flash à la création de l'annonce
            $session->getFlashBag()->add('notice', 'l\'annonce à bien été modifiée');

            // Redirection vers la page de l'annonce nouvellement créee
            return $this->redirectToRoute('oc_symfony_platform_view', array(
                'slug' => $advert->getSlug(),
                'id' => $id
            ));
        }

        // Si ce n'est pas POST
        return $this->render('OCSymfonyPlatformBundle:Advert:edit.html.twig', array(
            'form' => $form->createView(),
            'advert' => $advert
            ));
    }

    /**
     * @param Request $request
     * @param Session $session
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function addAction(Request $request, Session $session) {

        /*
        // Vérification du role de l'utilisateur
        if (!$this->get('security.authorization_checker')->isGranted('ROLE_AUTEUR')) {

            // Génère une page "Accès refusé"
            throw new AccessDeniedException('Accès limités aux auteurs');
        }
        */

        // Accès à l'EntityManager
        $em = $this->getDoctrine()->getManager();

        // Création de l'entité Advert
        $advert = new Advert();

        // Création du formulaire de création d'annonce
        $form = $this->createForm(AdvertType::class, $advert);

        // Si la requête est en POST création du lien Requête <-> Formulaire
        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

            $em->persist($advert);
            $em->flush();

            // Création d'un message flash à la création de l'annonce
            $session->getFlashBag()->add('notice', 'l\'annonce à bien été enregistrée');

            // Redirection vers la page de l'annonce nouvellement créee
            return $this->redirectToRoute('oc_symfony_platform_view', array('slug' => $advert->getSlug()));

        }

        // Si ce n'est pas POST
        return $this->render('OCSymfonyPlatformBundle:Advert:add.html.twig', array('form' => $form->createView()));

    }

    /**
     * @param Advert $advert
     * @return Response
     *
     * @ParamConverter("advert", options={"mapping": {"slug": "slug"}})
     */
    public function viewAction(Advert $advert) {

        // Récupération du repository
        $em = $this->getDoctrine()->getManager();

        // Récupération de la liste de candidatures de cette annonce
        $listApply = $em
            ->getRepository('OCSymfonyPlatformBundle:Application')
            ->findBy(array('advert' => $advert));

        // Récupération de la liste des compétences
        $listAdvertSkill = $em
            ->getRepository('OCSymfonyPlatformBundle:AdvertSkill')
            ->findBy(array('advert' => $advert));

        return $this->render('OCSymfonyPlatformBundle:Advert:view.html.twig', array(
            'advert' => $advert,
            'listApply' => $listApply,
            'listAdvertSkill' => $listAdvertSkill
        ));
    }

    Public function indexAction($page) {

        if ($page < 1) {
            throw new NotFoundHttpException('La page "'.$page.'" n\'existe pas');
        }

        $nbPerPage = 3;

        // Accès à l'EntityManager
        $em = $this->getDoctrine()->getManager();

        // Récupération de toutes les annonces
        $listAdverts = $em->getRepository('OCSymfonyPlatformBundle:Advert')->getAdverts($page, $nbPerPage);

        // Calcul du nombre total de pages necessaires
        $nbPages = ceil(count($listAdverts) / $nbPerPage);

        if ($page > $nbPages) {
            throw $this->createNotFoundException("La page" .$page. " n'existe pas.");
        }

        // Appel du template et passage des annonces en paramètres
        return $this->render('OCSymfonyPlatformBundle:Advert:index.html.twig', array(
            'listAdverts' => $listAdverts,
            'nbPages' => $nbPages,
            'page' => $page,
        ));
    }

    public function translationAction($name) {
        return $this->render('OCSymfonyPlatformBundle:Advert:translation.html.twig', array('name' => $name));
    }
}

src/OCSymfony/PlatformBundle/Resources/views/Advert/add.html.twig
{% extends "OCSymfonyPlatformBundle::layout.html.twig" %}

{% block title %}{{ parent() }} - Ajouter une annonce {% endblock %}

{% block body %}
    <h2>Ajouter une annonce</h2>

    {{ include('OCSymfonyPlatformBundle:Advert:form.html.twig') }}

    <p>
        Attention : cette annonce sera ajoutée directement sur la page d'accueil après validation du formulaire.
    </p>
{% endblock %}

src/OCSymfony/PlatformBundle/Resources/views/Advert/delete.html.twig
{% extends "OCSymfonyPlatformBundle::layout.html.twig" %}

{% block title %}
    Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}
    <h2>Supprimer une annonce</h2>

    <p>Etes vous certain de vouloir supprilmer l'annonce "{{ advert.title }} ?</p>

    <form action="{{ path('oc_symfony_platform_delete', {'id' : advert.id}) }}" method="post">
        <a href="{{ path('oc_symfony_platform_view', {'slug' : advert.slug }) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
        <input type="submit" value="Supprimer" class="btn btn-danger" />

        {{ form_rest(form) }}
    </form>
{% endblock %}

src/OCSymfony/PlatformBundle/Resources/views/Advert/edit.html.twig
{% extends "OCSymfonyPlatformBundle::layout.html.twig" %}

{% block title %}
    Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}
    <h2>Modifier une annonce</h2>

    {{ include('OCSymfonyPlatformBundle:Advert:form.html.twig') }}

    <div class="well">
        {{ advert.content }}
    </div>

    <p>
        Vous éditez une annonce déjà existante, merci de ne pas changer l'esprit général de l'annonce déjà publiée.
    </p>

    <p>
        <a href="{{ path('oc_symfony_platform_view', {'slug': advert.slug}) }}" class="btn btn-default">
            <i class="glyphicon glyphicone-chevron-left"></i>
            Retour à l'annonce
        </a>
    </p>

{% endblock %}

src/OCSymfony/PlatformBundle/Resources/views/Advert/form.html.twig
<h3>Formulaire d'annonce</h3>

<div class="well">
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}

    {# Génération du label + error + widget pour un champ. #}
    {% if form.date is defined %}
    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.date, "Date de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.date) }}

        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.date) }}
        </div>
    </div>
    {% endif %}


    {# Génération manuelle et éclatée : #}
    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.title, "Titre de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.title) }}

        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>


    {# Idem pour un autre champ. #}
    <div class="form-group">
        {{ form_label(form.content, "Contenu de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.title) }}
        <div class="col-sm-10">
            {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.author, "Auteur de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.author) }}

        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.author, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    {% if form.published is defined %}
    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.published, "Publication direct", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.published) }}

        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.published) }}
        </div>
    </div>
    {% endif %}

    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.image, "Ajout d'un fichier", {'label_attr': {'class': 'col-sm-2'}}) }}

        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.image) }}

        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.image) }}
        </div>
    </div>

    {{ form_widget(form.categories) }}
    <a href="#" id="add_category" class="btn btn-default">Ajouter une catégorie</a>

    {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

    {# Génération automatique des champs pas encore écrits.
       Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
       et tous les champs cachés (type « hidden »). #}
    {{ form_rest(form) }}

    {# Fermeture de la balise <form> du formulaire HTML #}
    {{ form_end(form) }}
</div>

{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
   mais si vous l'avez en local, changez simplement l'adresse. #}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

{# Voici le script en question : #}
<script type="text/javascript">
    $(document).ready(function() {
        // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
        var $container = $('div#ocsymfony_platformbundle_advert_categories');

        // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
        var index = $container.find(':input').length;

        // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
        $('#add_category').click(function(e) {
            addCategory($container);
            e.preventDefault(); // évite qu'un # apparaisse dans l'URL
            return false;
        });
        // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
        if (index == 0) {
            addCategory($container);
        } else {
            // S'il existe déjà des catégories, on ajoute un lien de suppression pour chacune d'entre elles
            $container.children('div').each(function() {
                addDeleteLink($(this));
            });
        }
        // La fonction qui ajoute un formulaire CategoryType
        function addCategory($container) {
            // Dans le contenu de l'attribut « data-prototype », on remplace :
            // - le texte "__name__label__" qu'il contient par le label du champ
            // - le texte "__name__" qu'il contient par le numéro du champ
            var template = $container.attr('data-prototype')
                .replace(/__name__label__/g, 'Catégorie n°' + (index+1))
                .replace(/__name__/g,        index)
            ;
            // On crée un objet jquery qui contient ce template
            var $prototype = $(template);
            // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
            addDeleteLink($prototype);
            // On ajoute le prototype modifié à la fin de la balise <div>
            $container.append($prototype);
            // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
            index++;
        }
        // La fonction qui ajoute un lien de suppression d'une catégorie
        function addDeleteLink($prototype) {
            // Création du lien
            var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');
            // Ajout du lien
            $prototype.append($deleteLink);
            // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
            $deleteLink.click(function(e) {
                $prototype.remove();
                e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                index--;
                return false;
            });
        }
    });
</script>

src/OCSymfony/PlatformBundle/Resources/views/Advert/index.html.twig
{% extends "OCSymfonyPlatformBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    {% for message in app.session.flashbag.get('notice') %}
        <p class="alert alert-info">{{ message }}</p>
    {% endfor %}

    <h2>Liste des annonces</h2>

    <ul>
        {% for advert in listAdverts %}
            <li>
                <a href="{{ path('oc_symfony_platform_view', {'slug': advert.slug}) }}">{{ advert.title }}</a> par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}
            </li>
        {% else %}
            <li>Il n'y a pas encore d'annonces !</li>
        {% endfor %}
    </ul>
    <ul class="pagination">
        {% for p in range(1, nbPages) %}
           <li{% if p == page %} class="active" {% endif %}>
               <a href="{{ path('oc_symfony_platform_homepage', {'page' : p}) }}">{{ p }}</a>
           </li>
        {% endfor %}
    </ul>
{% endblock %}

src/OCSymfony/PlatformBundle/Resources/views/Advert/menu.html.twig
<ul class="nav nav-pills nav-stacked">
    {% for advert in listAdverts %}
        <li>
            <a href="{{ path('oc_symfony_platform_view', {'slug':advert.slug}) }}">
                {{ advert.title }}
            </a>
        </li>
    {% endfor %}
</ul>

src/OCSymfony/PlatformBundle/Resources/views/Advert/translation.html.twig
<html>
    <body>
        {{ "Hello"|trans({'%name%': name}) }}
    {% trans %}site.devise{% endtrans %}
    </body>
</html>

src/OCSymfony/PlatformBundle/Resources/views/Advert/view.html.twig
{% extends "OCSymfonyPlatformBundle::layout.html.twig" %}

{% block title %}
    Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}
    {% if advert.image is not null %}
        <img src="{{ asset(advert.image.webPath) }}" alt="{{ advert.image.alt }}">
    {% endif %}
    <h2>{{ advert.title }}</h2>
    <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

    <div class="well">
        {{ advert.content }}
    </div>

    {% if not advert.categories.empty %}
        <p>
            Cette annonce est parue dans les catégories suivantes :
            {% for category in advert.categories %}
                {{ category.name }}{% if not loop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% endif %}

    {% if listAdvertSkill|length > 0 %}
        <div>
            <p>Cette annonce requiert les compétences suivantes : </p>
            <ul>
                {% for advertSkill in listAdvertSkill %}
                    <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    {% for message in app.session.flashbag.get('info') %}
        <p class="alert alert-info">{{ message }}</p>
    {% endfor %}
    <p>
        <a href="{{ path('oc_symfony_platform_homepage') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>

        <a href="{{ path('oc_symfony_platform_edit', {'id' : advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Modifier l'annonce
        </a>

        <a href="{{ path('oc_symfony_platform_delete', {'id' : advert.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Supprimer l'annonce
        </a>
    </p>

{% endblock %}